// English UI strings for MNR Poultry Management System

const en = {
  appName:    'MNR Poultry',
  appTagline: 'Management System',

  nav: {
    dashboard: 'Dashboard',
    sheds:     'Sheds',
    ponds:     'Ponds',
    feed:      'Feed',
    eggs:      'Eggs',
  },

  common: {
    add:            'Add',
    edit:           'Edit',
    delete:         'Delete',
    save:           'Save',
    saving:         'Saving…',
    cancel:         'Cancel',
    loading:        'Loading…',
    noData:         'No data',
    all:            'All',
    import:         'Import',
    export:         'Export',
    records:        'records',
    date:           'Date',
    notes:          'Notes',
    optional:       'optional',
    party:          'Supplier / Buyer',
    invoiceNo:      'Invoice No.',
    vehicleNo:      'Vehicle No.',
    totalAmount:    'Total Amount',
    netPL:          'Net P&L',
    revenue:        'Revenue',
    cost:           'Cost',
    supplier:       'Supplier',
    buyer:          'Buyer',
    viewAll:        'View all',
    recent:         'Recent',
    overview:       'Overview',
    actions:        'Actions',
    type:           'Type',
    category:       'Category',
    status:         'Status',
    name:           'Name',
    confirm_delete: 'Delete this record?',
    saving_msg:     'Saving…',
    update:         'Update',
    logTransaction: 'Log Transaction',
    logMovement:    'Log Movement',
    remarks:        'Any remarks',
  },

  auth: {
    login:       'Login',
    logout:      'Logout',
    email:       'Email',
    password:    'Password',
    loginBtn:    'Sign In',
    logging:     'Signing in…',
    loginFailed: 'Login failed. Check your email / password.',
    tagline:     'Manage your poultry business efficiently',
    welcomeBack: 'Welcome Back',
    accessOnly:  'Authorised users only',
  },

  dashboard: {
    title:        'Dashboard',
    subtitle:     'Overview of all operations — sheds, ponds, feed & eggs',
    addFeedEntry: '+ Feed Entry',
    addEggEntry:  '+ Egg Entry',
    addPondEntry: '+ Pond Entry',
    shedOverview: 'Shed Overview',
    pondOverview: 'Pond Overview',
    feedOverview: 'Feed Overview',
    eggOverview:  'Egg Overview',
    overallPL:    'Overall Net Profit / Loss',
    totalRevenue: 'Total Revenue',
    totalCost:    'Total Cost',
    recentFeed:   'Recent Feed Transactions',
    recentEggs:   'Recent Egg Transactions',
    loadingData:  'Loading data…',
  },

  shed: {
    title:           'Shed Management',
    subtitle:        'Manage sheds, chicken counts & movements',
    addShed:         '+ Add Shed',
    editShed:        'Edit Shed',
    shedName:        'Shed Name',
    shedType:        'Shed Type',
    capacity:        'Capacity (birds)',
    currentCount:    'Current Count (birds)',
    breed:           'Breed',
    placementDate:   'Placement Date',
    status:          'Status',
    utilised:        '% utilised',
    noSheds:         'No sheds added yet.',
    totalSheds:      'Total Sheds',
    totalChickens:   'Total Chickens',
    utilisation:     'Utilisation',
    emptySheds:      'Empty Sheds',
    available:       'available',
    active:          'active',
    empty:           'empty',
    maintenance:     'maintenance',
    broiler:         'Broiler',
    layer:           'Layer',
    breeder:         'Breeder',
    chick:           'Chick',
    other:           'Other',
    confirmDelete:   'Delete this shed? Movement history will be kept.',
    sheds:           'Sheds',
    movements:       'Movements',
    movementLog:     'Movement Log',
    logMovement:     'Log Movement',
    movementType:    'Movement Type',
    birdCount:       'No. of Birds',
    placement:       'Placement',
    harvest:         'Harvest',
    mortality:       'Mortality',
    transfer:        'Transfer',
    placementDesc:   'Add birds to shed',
    harvestDesc:     'Birds sold / removed',
    mortalityDesc:   'Birds died',
    transferDesc:    'Moved to another shed',
    birdsNow:        'birds currently',
    addShedTitle:    'Add New Shed',
    updateShed:      'Update Shed',
    shedPlaceholder: 'e.g. Shed A',
    breedPlaceholder:'e.g. Ross 308',
    notesPlaceholder:'Any remarks about this shed',
  },

  feed: {
    title:           'Feed Management',
    subtitle:        'Track all feed import & export transactions',
    addTx:           '+ Add Transaction',
    newTx:           'New Feed Transaction',
    totalImported:   'Total Imported',
    totalExported:   'Total Exported',
    currentStock:    'Current Stock',
    pricePerKg:      '₹ / kg',
    quantityKg:      'Quantity (kg)',
    category:        'Category',
    corn:            'Corn',
    soybean:         'Soybean',
    wheat:           'Wheat',
    premix:          'Premix',
    riceBran:        'Rice Bran',
    other:           'Other',
    totalReceived:   'Total received',
    totalDispatched: 'Total dispatched',
    filterAll:       'All',
    importLabel:     'Import',
    exportLabel:     'Export',
    tableType:       'Type',
    tableDate:       'Date',
    tableCategory:   'Category',
    tableParty:      'Party',
    tableQty:        'Qty (kg)',
    tableRate:       '₹/kg',
    tableTotal:      'Total',
    tableInvoice:    'Invoice',
    tableActions:    'Actions',
    noTx:            'No transactions found',
  },

  eggs: {
    title:          'Egg Management',
    subtitle:       'Track all egg import & export transactions',
    addTx:          '+ Add Transaction',
    newTx:          'New Egg Transaction',
    totalImported:  'Eggs Imported',
    totalExported:  'Eggs Exported',
    currentStock:   'Current Stock',
    pricePerTray:   '₹ / tray',
    quantityTrays:  'Quantity (trays)',
    trayInfo:       '1 tray = 30 eggs',
    eggsImported:   'Eggs Imported',
    eggsExported:   'Eggs Exported',
    netRevenue:     'Net Revenue',
    whiteEgg:       'White Egg',
    brownEgg:       'Brown Egg',
    countryEgg:     'Country Egg',
    brokenEgg:      'Broken Egg',
    other:          'Other',
    trays:          'trays',
    eggs:           'eggs',
    tableTrays:     'Trays',
    tableEggs:      'Eggs',
    tableRate:      '₹/Tray',
    noTx:           'No transactions found',
  },

  pond: {
    title:             'Pond Management',
    subtitle:          'Fish & prawn ponds — seed, feed, harvest & more',
    addPond:           '+ Add Pond',
    editPond:          'Edit Pond',
    addPondTitle:      'Add New Pond',
    updatePond:        'Update Pond',
    pondName:          'Pond Name',
    pondType:          'Pond Type',
    fish:              'Fish',
    prawn:             'Prawn',
    species:           'Species',
    areaAcres:         'Area (Acres)',
    depthFt:           'Avg Depth (ft) – optional',
    capacityKg:        'Capacity (kg)',
    currentStockKg:    'Current Stock (kg)',
    stockingDate:      'Stocking Date',
    status:            'Status',
    active:            'active',
    harvested:         'harvested',
    fallow:            'fallow',
    maintenance:       'maintenance',
    totalPonds:        'Total Ponds',
    liveStock:         'Live Stock',
    totalHarvest:      'Total Harvest',
    pondPL:            'Pond P&L',
    estimatedWt:       'estimated weight',
    cumulative:        'cumulative',
    fillRate:          'fill rate',
    utilised:          '% utilised',
    noPonds:           'No ponds added yet.',
    fcr:               'FCR',
    confirmDelete:     'Delete this pond? Transaction history will remain.',
    ponds:             'Ponds',
    transactions:      'Transactions',
    logTx:             'Log Transaction',
    txType:            'Transaction Type',
    seedStock:         'Seed Stocking',
    feedIn:            'Feed Input',
    harvest:           'Harvest (Sale)',
    mortality:         'Mortality',
    chemical:          'Chemical / Medicine',
    seedStockDesc:     'Buy fingerlings/seeds and stock pond',
    feedInDesc:        'Feed purchased and fed to fish/prawns',
    harvestDesc:       'Fish/prawns harvested and sold',
    mortalityDesc:     'Record deaths — reduces live stock',
    chemicalDesc:      'Medicines, lime, probiotics, disinfectants',
    seedCount:         'No. of Seeds / Fingerlings',
    avgWeight:         'Avg Weight per Seed (g) – optional',
    stockedWt:         'Stocked Weight (kg) – optional',
    feedType:          'Feed Type',
    itemName:          'Item Name',
    unit:              'Unit',
    quantity:          'Quantity',
    pricePerUnit:      '₹ / unit',
    pricePerKg:        '₹ / kg',
    harvestedWt:       'Harvested Weight (kg)',
    wtLost:            'Estimated Weight Lost (kg)',
    saleAmount:        'Sale Amount',
    totalCost:         'Total Cost',
    stocked:           'Stocked',
    noTx:              'No transactions found',
    liveStockNow:      'Live stock',
    tableDate:         'Date',
    tablePond:         'Pond',
    tableType:         'Type',
    tableDetails:      'Details',
    tableQty:          'Qty/Count',
    tableRate:         'Rate',
    tableTotal:        'Total',
    tableParty:        'Party',
    tableActions:      'Actions',
    allPonds:          'All Ponds',
    supplierName:      'Supplier name',
    buyerMarket:       'Buyer / market name',
    pellets:           'e.g. Pellets, Organic',
    seedCountPlaceholder: '5000',
    computedFromCount: 'If blank: computed from count × avg weight',
  },

  stats: {
    feedImported:     'Feed Imported',
    feedExported:     'Feed Exported',
    feedStock:        'Feed Stock',
    feedPL:           'Feed P&L',
    eggImported:      'Eggs Imported',
    eggExported:      'Eggs Exported',
    eggStock:         'Egg Stock',
    eggRevenue:       'Egg Revenue',
    totalReceived:    'Total received',
    totalDispatched:  'Total dispatched',
    currentInventory: 'Current inventory',
    totalSheds:       'Total Sheds',
    totalChickens:    'Total Chickens',
    utilisation:      'Utilisation',
    emptySheds:       'Empty Sheds',
    available:        'available',
    totalPonds:       'Total Ponds',
    liveStock:        'Live Stock',
    harvestRev:       'Harvest Revenue',
    pondPL:           'Pond P&L',
    fillRate:         'fill rate',
  },
} as const

export default en
