// Telugu UI strings for MNR Poultry Management System
// తెలుగు అనువాదాలు — MNR పౌల్ట్రీ నిర్వహణ వ్యవస్థ

const te = {
  // ── App meta ────────────────────────────────────────────────────────────
  appName:        'MNR పౌల్ట్రీ',
  appTagline:     'నిర్వహణ వ్యవస్థ',

  // ── Nav ─────────────────────────────────────────────────────────────────
  nav: {
    dashboard: 'డాష్‌బోర్డ్',
    sheds:     'షెడ్లు',
    ponds:     'చెరువులు',
    feed:      'దాణా',
    eggs:      'గుడ్లు',
  },

  // ── Common ───────────────────────────────────────────────────────────────
  common: {
    add:           'జోడించు',
    edit:          'సవరించు',
    delete:        'తొలగించు',
    save:          'సేవ్ చేయి',
    saving:        'సేవ్ అవుతోంది…',
    cancel:        'రద్దు చేయి',
    loading:       'లోడ్ అవుతోంది…',
    noData:        'డేటా లేదు',
    all:           'అన్నీ',
    import:        'దిగుమతి',
    export:        'ఎగుమతి',
    records:       'రికార్డులు',
    date:          'తేదీ',
    notes:         'గమనికలు',
    optional:      'ఐచ్ఛికం',
    party:         'సప్లయర్ / కొనుగోలుదారు',
    invoiceNo:     'ఇన్వాయిస్ నం.',
    vehicleNo:     'వాహన నం.',
    totalAmount:   'మొత్తం మొత్తం',
    netPL:         'లాభ/నష్టం',
    revenue:       'ఆదాయం',
    cost:          'ఖర్చు',
    supplier:      'సప్లయర్',
    buyer:         'కొనుగోలుదారు',
    viewAll:       'అన్నీ చూడు',
    recent:        'తాజా',
    overview:      'సమీక్ష',
    actions:       'చర్యలు',
    type:          'రకం',
    category:      'వర్గం',
    status:        'స్థితి',
    name:          'పేరు',
    confirm_delete: 'ఈ రికార్డ్ తొలగించాలా?',
    saving_msg:    'సేవ్ అవుతోంది…',
    update:        'నవీకరించు',
    logTransaction: 'లావాదేవీ నమోదు చేయి',
    logMovement:   'కదలిక నమోదు చేయి',
    remarks:       'వ్యాఖ్యలు',
  },

  // ── Auth ─────────────────────────────────────────────────────────────────
  auth: {
    login:         'లాగిన్',
    logout:        'లాగ్అవుట్',
    email:         'ఇమెయిల్',
    password:      'పాస్‌వర్డ్',
    loginBtn:      'లాగిన్ చేయి',
    logging:       'లాగిన్ అవుతోంది…',
    loginFailed:   'లాగిన్ విఫలమైంది. ఇమెయిల్ / పాస్‌వర్డ్ తనిఖీ చేయండి.',
    tagline:       'మీ పౌల్ట్రీ వ్యాపారాన్ని సమర్థంగా నిర్వహించండి',
    welcomeBack:   'స్వాగతం',
    accessOnly:    'అధికారం పొందిన వినియోగదారులు మాత్రమే',
  },

  // ── Dashboard ─────────────────────────────────────────────────────────────
  dashboard: {
    title:         'డాష్‌బోర్డ్',
    subtitle:      'అన్ని కార్యకలాపాల సమీక్ష — షెడ్లు, చెరువులు, దాణా & గుడ్లు',
    addFeedEntry:  '+ దాణా ఎంట్రీ',
    addEggEntry:   '+ గుడ్లు ఎంట్రీ',
    addPondEntry:  '+ చెరువు ఎంట్రీ',
    shedOverview:  'షెడ్ సమీక్ష',
    pondOverview:  'చెరువు సమీక్ష',
    feedOverview:  'దాణా సమీక్ష',
    eggOverview:   'గుడ్లు సమీక్ష',
    overallPL:     'మొత్తం లాభ / నష్టం',
    totalRevenue:  'మొత్తం ఆదాయం',
    totalCost:     'మొత్తం ఖర్చు',
    recentFeed:    'తాజా దాణా లావాదేవీలు',
    recentEggs:    'తాజా గుడ్లు లావాదేవీలు',
    loadingData:   'డేటా లోడ్ అవుతోంది…',
  },

  // ── Shed ─────────────────────────────────────────────────────────────────
  shed: {
    title:         'షెడ్ నిర్వహణ',
    subtitle:      'షెడ్లు, కోళ్ల సంఖ్య & కదలికలు నిర్వహించు',
    addShed:       '+ షెడ్ జోడించు',
    editShed:      'షెడ్ సవరించు',
    shedName:      'షెడ్ పేరు',
    shedType:      'షెడ్ రకం',
    capacity:      'సామర్థ్యం (పక్షులు)',
    currentCount:  'ప్రస్తుత సంఖ్య (పక్షులు)',
    breed:         'జాతి',
    placementDate: 'స్థాపన తేదీ',
    status:        'స్థితి',
    utilised:      '% ఉపయోగంలో ఉంది',
    noSheds:       'షెడ్లు ఏవీ జోడించబడలేదు.',
    totalSheds:    'మొత్తం షెడ్లు',
    totalChickens: 'మొత్తం కోళ్లు',
    utilisation:   'వినియోగం',
    emptySheds:    'ఖాళీ షెడ్లు',
    available:     'అందుబాటులో ఉంది',
    active:        'క్రియాశీలం',
    empty:         'ఖాళీ',
    maintenance:   'నిర్వహణ',
    broiler:       'బ్రాయిలర్',
    layer:         'లేయర్',
    breeder:       'బ్రీడర్',
    chick:         'పిల్ల కోళ్లు',
    other:         'ఇతర',
    confirmDelete: 'ఈ షెడ్ తొలగించాలా? కదలిక చరిత్ర ఉంచబడుతుంది.',
    sheds:         'షెడ్లు',
    movements:     'కదలికలు',
    movementLog:   'కదలిక నమోదు',
    logMovement:   'కదలిక నమోదు చేయి',
    movementType:  'కదలిక రకం',
    birdCount:     'పక్షుల సంఖ్య',
    placement:     'స్థాపన',
    harvest:       'కోత',
    mortality:     'మరణాలు',
    transfer:      'బదిలీ',
    placementDesc: 'షెడ్‌లో పక్షులు జోడించు',
    harvestDesc:   'పక్షులను విక్రయించారు/తొలగించారు',
    mortalityDesc: 'మరణించిన పక్షులు',
    transferDesc:  'మరొక షెడ్‌కు తరలించారు',
    birdsNow:      'పక్షులు ప్రస్తుతం',
    addShedTitle:  'కొత్త షెడ్ జోడించు',
    updateShed:    'షెడ్ నవీకరించు',
    shedPlaceholder: 'ఉదా: షెడ్ A',
    breedPlaceholder: 'ఉదా: రాస్ 308',
    notesPlaceholder: 'షెడ్ గురించి వ్యాఖ్యలు',
  },

  // ── Feed ─────────────────────────────────────────────────────────────────
  feed: {
    title:         'దాణా నిర్వహణ',
    subtitle:      'అన్ని దాణా దిగుమతి & ఎగుమతి లావాదేవీలు నిర్వహించు',
    addTx:         '+ లావాదేవీ జోడించు',
    newTx:         'కొత్త దాణా లావాదేవీ',
    totalImported: 'మొత్తం దిగుమతి',
    totalExported: 'మొత్తం ఎగుమతి',
    currentStock:  'ప్రస్తుత నిల్వ',
    pricePerKg:    '₹ / కిలో',
    quantityKg:    'పరిమాణం (కిలో)',
    category:      'వర్గం',
    corn:          'మొక్కజొన్న',
    soybean:       'సోయాబీన్',
    wheat:         'గోధుమ',
    premix:        'ప్రీమిక్స్',
    riceBran:      'అన్నపు తవుడు',
    other:         'ఇతర',
    totalReceived: 'మొత్తం స్వీకరించింది',
    totalDispatched: 'మొత్తం పంపింది',
    filterAll:     'అన్నీ',
    importLabel:   'దిగుమతి',
    exportLabel:   'ఎగుమతి',
    tableType:     'రకం',
    tableDate:     'తేదీ',
    tableCategory: 'వర్గం',
    tableParty:    'పక్షం',
    tableQty:      'పరి. (కిలో)',
    tableRate:     '₹/కిలో',
    tableTotal:    'మొత్తం',
    tableInvoice:  'ఇన్వాయిస్',
    tableActions:  'చర్యలు',
    noTx:          'లావాదేవీలు కనుగొనబడలేదు',
  },

  // ── Eggs ─────────────────────────────────────────────────────────────────
  eggs: {
    title:         'గుడ్లు నిర్వహణ',
    subtitle:      'అన్ని గుడ్లు దిగుమతి & ఎగుమతి లావాదేవీలు నిర్వహించు',
    addTx:         '+ లావాదేవీ జోడించు',
    newTx:         'కొత్త గుడ్లు లావాదేవీ',
    totalImported: 'మొత్తం దిగుమతి',
    totalExported: 'మొత్తం ఎగుమతి',
    currentStock:  'ప్రస్తుత నిల్వ',
    pricePerTray:  '₹ / ట్రే',
    quantityTrays: 'పరిమాణం (ట్రేలు)',
    trayInfo:      '1 ట్రే = 30 గుడ్లు',
    eggsImported:  'గుడ్లు దిగుమతి',
    eggsExported:  'గుడ్లు ఎగుమతి',
    netRevenue:    'నికర ఆదాయం',
    whiteEgg:      'తెల్ల గుడ్డు',
    brownEgg:      'గోధుమ గుడ్డు',
    countryEgg:    'దేశం గుడ్డు',
    brokenEgg:     'విరిగిన గుడ్డు',
    other:         'ఇతర',
    trays:         'ట్రేలు',
    eggs:          'గుడ్లు',
    tableTrays:    'ట్రేలు',
    tableEggs:     'గుడ్లు',
    tableRate:     '₹/ట్రే',
    noTx:          'లావాదేవీలు కనుగొనబడలేదు',
  },

  // ── Pond ─────────────────────────────────────────────────────────────────
  pond: {
    title:         'చెరువు నిర్వహణ',
    subtitle:      'చేప & రొయ్యల చెరువులు — విత్తనం, దాణా, కోత & మరిన్ని',
    addPond:       '+ చెరువు జోడించు',
    editPond:      'చెరువు సవరించు',
    addPondTitle:  'కొత్త చెరువు జోడించు',
    updatePond:    'చెరువు నవీకరించు',
    pondName:      'చెరువు పేరు',
    pondType:      'చెరువు రకం',
    fish:          'చేప',
    prawn:         'రొయ్య',
    species:       'జాతి',
    areaAcres:     'వైశాల్యం (ఎకరాలు)',
    depthFt:       'లోతు (అడుగులు) — ఐచ్ఛికం',
    capacityKg:    'సామర్థ్యం (కిలో)',
    currentStockKg: 'ప్రస్తుత నిల్వ (కిలో)',
    stockingDate:  'స్టాకింగ్ తేదీ',
    status:        'స్థితి',
    active:        'క్రియాశీలం',
    harvested:     'కోత పూర్తైంది',
    fallow:        'పౌరాణిక',
    maintenance:   'నిర్వహణ',
    totalPonds:    'మొత్తం చెరువులు',
    liveStock:     'సజీవ నిల్వ',
    totalHarvest:  'మొత్తం కోత',
    pondPL:        'చెరువు లాభ/నష్టం',
    estimatedWt:   'అంచనా బరువు',
    cumulative:    'సంచిత',
    fillRate:      'నింపే రేటు',
    utilised:      '% ఉపయోగంలో ఉంది',
    noPonds:       'చెరువులు ఏవీ జోడించబడలేదు.',
    fcr:           'FCR',
    confirmDelete: 'ఈ చెరువు తొలగించాలా? లావాదేవీ చరిత్ర ఉంచబడుతుంది.',
    ponds:         'చెరువులు',
    transactions:  'లావాదేవీలు',
    logTx:         'లావాదేవీ నమోదు',
    txType:        'లావాదేవీ రకం',
    seedStock:     'విత్తన స్టాకింగ్',
    feedIn:        'దాణా ఇన్పుట్',
    harvest:       'కోత (విక్రయం)',
    mortality:     'మరణాలు',
    chemical:      'రసాయనం / మందు',
    seedStockDesc: 'వేలుపిల్లలు/విత్తనాలు కొని చెరువులో వేయు',
    feedInDesc:    'చేప/రొయ్యలకు దాణా కొని వేయు',
    harvestDesc:   'చేప/రొయ్యలు కోసి అమ్మారు',
    mortalityDesc: 'మరణాలు నమోదు — సజీవ నిల్వ తగ్గుతుంది',
    chemicalDesc:  'మందులు, సున్నం, ప్రోబయోటిక్స్, క్రిమిసంహారిణులు',
    seedCount:     'విత్తనాల సంఖ్య',
    avgWeight:     'ఒక్కో విత్తనం సగటు బరువు (గ్రా)',
    stockedWt:     'స్టాక్ చేసిన బరువు (కిలో)',
    feedType:      'దాణా రకం',
    itemName:      'వస్తువు పేరు',
    unit:          'యూనిట్',
    quantity:      'పరిమాణం',
    pricePerUnit:  '₹ / యూనిట్',
    pricePerKg:    '₹ / కిలో',
    harvestedWt:   'కోత బరువు (కిలో)',
    wtLost:        'నష్టపోయిన బరువు (కిలో)',
    saleAmount:    'విక్రయ మొత్తం',
    totalCost:     'మొత్తం ఖర్చు',
    stocked:       'స్టాక్ తేదీ',
    noTx:          'లావాదేవీలు కనుగొనబడలేదు',
    liveStockNow:  'సజీవ నిల్వ ప్రస్తుతం',
    tableDate:     'తేదీ',
    tablePond:     'చెరువు',
    tableType:     'రకం',
    tableDetails:  'వివరాలు',
    tableQty:      'పరి./సంఖ్య',
    tableRate:     'రేటు',
    tableTotal:    'మొత్తం',
    tableParty:    'పక్షం',
    tableActions:  'చర్యలు',
    allPonds:      'అన్ని చెరువులు',
    supplierName:  'సప్లయర్ పేరు',
    buyerMarket:   'కొనుగోలుదారు / మార్కెట్',
    pellets:       'పెల్లెట్స్, సేంద్రియ',
    seedCountPlaceholder: '5000',
    computedFromCount: 'ఖాళీ అయితే: సంఖ్య × సగటు బరువు నుండి లెక్కిస్తారు',
  },

  // ── Stats card labels ─────────────────────────────────────────────────────
  stats: {
    feedImported:  'దిగుమతి దాణా',
    feedExported:  'ఎగుమతి దాణా',
    feedStock:     'దాణా నిల్వ',
    feedPL:        'దాణా లాభ/నష్టం',
    eggImported:   'దిగుమతి గుడ్లు',
    eggExported:   'ఎగుమతి గుడ్లు',
    eggStock:      'గుడ్లు నిల్వ',
    eggRevenue:    'గుడ్లు ఆదాయం',
    totalReceived: 'మొత్తం స్వీకరించింది',
    totalDispatched: 'మొత్తం పంపింది',
    currentInventory: 'ప్రస్తుత జాబితా',
    totalSheds:    'మొత్తం షెడ్లు',
    totalChickens: 'మొత్తం కోళ్లు',
    utilisation:   'వినియోగం',
    emptySheds:    'ఖాళీ షెడ్లు',
    available:     'అందుబాటులో',
    totalPonds:    'మొత్తం చెరువులు',
    liveStock:     'సజీవ నిల్వ',
    harvestRev:    'కోత ఆదాయం',
    pondPL:        'చెరువు లాభ/నష్టం',
    fillRate:      'నింపే రేటు',
  },
} as const

export default te
